# Generated by Django 4.2.4 on 2023-09-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private profile'),
        ),
    ]
