# Generated by Django 4.2.4 on 2023-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendList', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
    ]
