# Generated by Django 4.2.4 on 2023-08-12 15:49

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='image',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='chats/images/%d/%m/%Y', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='imagesofmessage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='chats/messages/images/%d/%m/%Y', verbose_name='Image'),
        ),
    ]
