# Generated by Django 4.2.4 on 2023-08-31 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_chat_image_alter_imagesofmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, null=True, verbose_name='Last Message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time of the last message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Chat Name', max_length=100, verbose_name='Chat Name'),
        ),
        migrations.CreateModel(
            name='ChatActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name="Text of chat's Action")),
                ('time', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Chat.chat', verbose_name='Chat')),
            ],
        ),
    ]
