# Generated by Django 4.2.4 on 2023-08-31 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0005_alter_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type_of',
            field=models.CharField(choices=[('Message', 'Message'), ('Action', 'Action')], default='Message', max_length=7, verbose_name='Type of message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='ChatActions',
        ),
    ]
