# Generated by Django 4.2.4 on 2023-08-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_message_type_of_alter_message_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='last_message_time',
        ),
    ]
