# Generated by Django 4.2.4 on 2023-09-01 05:47

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_remove_chat_last_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='chats/images/%d/%m/%Y', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat Name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='Chat.chat', verbose_name='Chat'),
        ),
    ]
